version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306:3306