// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"17-di/product"
	"database/sql"
	"github.com/google/wire"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func NewUseCase(db *sql.DB) *product.UseCase {
	repository := product.NewRepository(db)
	useCase := product.NewUseCase(repository)
	return useCase
}

// wire.go:

var setRepositoryDependency = wire.NewSet(product.NewRepository, wire.Bind(new(product.RepositoryInterface), new(*product.Repository)))
