POST http://localhost:8000/users/jwt
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "123456"
}

###
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "123456"
}

###
